/**
* ============================================
* @author:syf20020816@outlook.com
* @since:20231018
* @version:0.3.0
* @type:interface
* @description:
* # SAlert
* SAlert is used to display important prompt information on the page
* ## properties
* - in property <int> font-weight :font weight;
* - in property <length> font-size: font size;
* - in property <brush> font-color : font color;
* - in property <bool> font-italic : font italic;
* - in property <string> font-family : font family;
* - in property <TextOverflow> overflow : text overflow;
* - in property <length> spacing : spacing among icons and text in alert;
* - in-out property <string> text : display text in alert;
* - in-out property <bool> is-show : is alert show or not;
* - in property <length> alert-height : alert height;
* - in-out property <ResultType> result-type: the result type of the alert;
* - in property <image> close-icon : close icon;
* - in property <length> icon-size : icon size;
* ## functions
* - public function open() : open alert
* - public function close() : close alert
* - public function success(text:string) : open success alert
* - public function warning(text:string) : open warning alert
* - public function error(text:string) : open error alert
* - public function info(text:string) : open info alert
* - public function help(text:string) : open help alert
* - public function primary(text:string) : open primary alert 
* ============================================
*/

import { SCard } from "../card/index.slint";
import { SText } from "../text/index.slint";
import { SIcon } from "../icon/index.slint";
import { ROOT_STYLES, DefaultSAlertProps } from "../../themes/index.slint";
import { Themes,ResultType,UseIcons } from "../../use/index.slint";
export component Alert inherits Rectangle{
  height: 100%;
  width: 100%;
  opacity: 1;
  visible: is-show;
  z: 1111;
  in property <int> font-weight : DefaultSAlertProps.font-weight;
  in property <length> font-size: DefaultSAlertProps.font-size;
  in property <brush> font-color <=> content-text.color;
  in property <bool> font-italic : DefaultSAlertProps.font-italic;
  in property <string> font-family : DefaultSAlertProps.font-family;
  in property <TextOverflow> overflow : DefaultSAlertProps.overflow;
  in property <length> spacing : DefaultSAlertProps.spacing;
  in-out property <string> text : DefaultSAlertProps.text;
  in-out property <bool> is-show : DefaultSAlertProps.is-show;
  in property <length> alert-height : DefaultSAlertProps.alert-height;
  in-out property <ResultType> result-type: DefaultSAlertProps.result-type;
  in property <image> close-icon : DefaultSAlertProps.close-icon;
  in property <length> icon-size : DefaultSAlertProps.icon-size;
  in property <bool> custom-card-style: false;
  in property <brush> card-background: ROOT_STYLES.sur-theme-colors.success.normal;
  in property <brush> card-border-color: ROOT_STYLES.sur-theme-colors.success.normal;
  in property <brush> card-shadow-color: ROOT_STYLES.sur-theme-colors.success.deepest;
  in property <length> card-border-width: 2px;
  in property <length> card-border-radius: 4px;
  in property <brush> icon-color: root.font-color;
  private property <Themes> theme : Success;
  private property <image> icon : UseIcons.icons.Success;
  private property <brush> resolved-card-background: ROOT_STYLES.sur-theme-colors.success.normal;
  private property <brush> resolved-card-border-color: ROOT_STYLES.sur-theme-colors.success.normal;
  private property <brush> resolved-card-shadow-color: ROOT_STYLES.sur-theme-colors.success.deepest;
  public function open() {
      root.is-show = true;
  }
  public function close() {
    root.is-show = false;
  }
  public function success(text:string) {
    root.result-type = ResultType.Success;
    root.text = text;
    root.open(); 
  }
  public function warning(text:string) {
    root.result-type = ResultType.Warning;
    root.text = text;
    root.open(); 
  }
  public function error(text:string) {
    root.result-type = ResultType.Error;
    root.text = text;
    root.open(); 
  }
  public function info(text:string) {
    root.result-type = ResultType.Info;
    root.text = text;
    root.open(); 
  }
  public function help(text:string) {
    root.result-type = ResultType.Help;
    root.text = text;
    root.open(); 
  }
  public function primary(text:string) {
    root.result-type = ResultType.Primary;
    root.text = text;
    root.open(); 
  }
  
  states [
    primary when result-type==ResultType.Primary: {
      root.theme : Themes.Primary;
      root.icon : UseIcons.icons.Smiling-face;
      root.resolved-card-background: ROOT_STYLES.sur-theme-colors.primary.normal;
      root.resolved-card-border-color: ROOT_STYLES.sur-theme-colors.primary.normal;
      root.resolved-card-shadow-color: ROOT_STYLES.sur-theme-colors.primary.deepest;
    }
    success when result-type==ResultType.Success: {
      root.theme : Themes.Success;
      root.icon : UseIcons.icons.Success;
      root.resolved-card-background: ROOT_STYLES.sur-theme-colors.success.normal;
      root.resolved-card-border-color: ROOT_STYLES.sur-theme-colors.success.normal;
      root.resolved-card-shadow-color: ROOT_STYLES.sur-theme-colors.success.deepest;
    }
    info when result-type==ResultType.Info: {
      root.theme : Themes.Info;
      root.icon : UseIcons.icons.Info;
      root.resolved-card-background: ROOT_STYLES.sur-theme-colors.info.normal;
      root.resolved-card-border-color: ROOT_STYLES.sur-theme-colors.info.normal;
      root.resolved-card-shadow-color: ROOT_STYLES.sur-theme-colors.info.deepest;
    }
    warning when result-type==ResultType.Warning: {
      root.theme : Themes.Warning;
      root.icon : UseIcons.icons.Attention;
      root.resolved-card-background: ROOT_STYLES.sur-theme-colors.warning.normal;
      root.resolved-card-border-color: ROOT_STYLES.sur-theme-colors.warning.normal;
      root.resolved-card-shadow-color: ROOT_STYLES.sur-theme-colors.warning.deepest;
    }
    error when result-type==ResultType.Error: {
      root.theme : Themes.Error;
      root.icon : UseIcons.icons.Close-one;
      root.resolved-card-background: ROOT_STYLES.sur-theme-colors.error.normal;
      root.resolved-card-border-color: ROOT_STYLES.sur-theme-colors.error.normal;
      root.resolved-card-shadow-color: ROOT_STYLES.sur-theme-colors.error.deepest;
    }
    help when result-type==ResultType.Help: {
      root.theme : Themes.Light;
      root.icon : UseIcons.icons.Help;
      root.resolved-card-background: ROOT_STYLES.sur-theme-colors.light.normal;
      root.resolved-card-border-color: ROOT_STYLES.sur-theme-colors.light.normal;
      root.resolved-card-shadow-color: ROOT_STYLES.sur-theme-colors.light.deepest;
    }
  ]
  alert:=SCard { 
    y: 6px;
    clip: true;
    card-width: parent.width * 0.8;
    card-height: root.alert-height;
    theme: root.theme;
    background: root.custom-card-style ? root.card-background : root.resolved-card-background;
    border-color: root.custom-card-style ? root.card-border-color : root.resolved-card-border-color;
    drop-shadow-color: root.custom-card-style ? root.card-shadow-color : root.resolved-card-shadow-color;
    border-width: root.custom-card-style ? root.card-border-width : 2px;
    border-radius: root.custom-card-style ? root.card-border-radius : 4px;
    layuot := HorizontalLayout {
      padding-left: root.spacing;
      spacing: root.spacing;
      padding-right: root.spacing;
      Rectangle {
        width: type-icon.width;
        type-icon:=SIcon {
          theme: root.theme;
          colorize: root.custom-card-style ? root.icon-color : self.get-colorize();
          source: root.icon;
          height: root.icon-size;
          width: root.icon-size;
        }
      }
      content-text:=SText {
        theme: root.theme;
        text: root.text;
        font-family: root.font-family;
        font-size: root.font-size;
        font-italic: root.font-italic;
        font-weight: root.font-weight;
        overflow: root.overflow;
      }
      Rectangle {
        width: close-icon.width;
        close-icon:=SIcon {
          theme: root.theme;
          colorize: root.custom-card-style ? root.icon-color : self.get-colorize();
          source: root.close-icon;
          height: root.icon-size;
          width: root.icon-size;
          clicked => {
            root.close()
          }
        }
      }
    }
  }
}
